apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.SECRET.MONGO_INITDB_ROOT_USERNAME | b64enc | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.SECRET.MONGO_INITDB_ROOT_PASSWORD | b64enc | quote }}
  MONGODB_USER: {{ .Values.SECRET.MONGODB_USER | b64enc | quote }}
  MONGODB_PASSWORD: {{ .Values.SECRET.MONGODB_PASSWORD | b64enc | quote }}
  MONGO_INITDB_DATABASE: {{ .Values.SECRET.MONGO_INITDB_DATABASE | b64enc | quote }}
  DB_HOST: {{ .Values.SECRET.DB_HOST | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-keyfile
  labels:
    app: mongodb
type: Opaque
data:
  mongo-keyfile: {{ .Values.SECRET.KEYFILE | b64enc | quote }}
